name: Build V8

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  release:
    types: [published]

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_android:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, arm, x64, x86]

    name: "android"
    #runs-on: ubuntu-latest
    runs-on: Ubuntu 22.04.4 LTS
    steps:
      - name: Show ubuntu libraries
        run: |
          if [[ -d "/usr/lib/i386-linux-gnu" ]]; then
            echo "/usr/lib/i386-linux-gnu exists."
            ls -la /usr/lib/i386-linux-gnu/libatomic.so.1*
          else
            echo "/usr/lib/i386-linux-gnu doesn't not exist."
          fi

          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libstdc++6:i386 libatomic1:i386

          if [[ -d "/usr/lib/i386-linux-gnu" ]]; then
            echo "/usr/lib/i386-linux-gnu exists."
            ls -la /usr/lib/i386-linux-gnu/
            ls -la /usr/lib/i386-linux-gnu/libatomic.so.1*
          else
            echo "/usr/lib/i386-linux-gnu doesn't not exist."
          fi

          if [[ -d "/usr/lib/x86_64-linux-gnu" ]]; then
            echo "/usr/lib/x86_64-linux-gnu exists."
            ls -la /usr/lib/x86_64-linux-gnu/libatomic.so.1*
          else
            echo "/usr/lib/x86_64-linux-gnu doesn't not exist."
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NDK r23c
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23c
          add-to-path: false
          local-cache: true

      - name: Clone DepotTools
        run: |
            cd ..
            DEPOT_TOOLS_PATH=$(pwd)/depot_tools
            git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
            echo "DEPOT_TOOLS_PATH=$DEPOT_TOOLS_PATH" >> $GITHUB_ENV
            echo "DEPOT_TOOLS_PATH=$DEPOT_TOOLS_PATH"

      - name: Print env
        run: |
          echo "${{ env.DEPOT_TOOLS_PATH }}"
          ls -l ${{ env.DEPOT_TOOLS_PATH }}

      - name: Install gn
        run: |
          wget https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/latest -O ./gn.zip
          unzip gn.zip -d buildtools/linux64/

      - name: Install ninja
        run: |
          if ! command -v ninja &> /dev/null; then
              echo "Ninja not found, installing..."
              # sudo apt update
              sudo apt install ninja-build
          else
              echo "Ninja is already installed."
          fi
          which ninja
          NINJA_PATH=$(which ninja)
          CURRENT_DIR=$(pwd)
          mkdir -p ${CURRENT_DIR}/third_party/ninja
          ln -s ${NINJA_PATH} ${CURRENT_DIR}/third_party/ninja/ninja

      - name: Install linux sysroot
        run: |
          if [[ "${{ matrix.arch }}" == "arm64" || "${{ matrix.arch }}" == "x64" ]];then
            INSTALL_SYSROOT_ARCH="amd64"
          else
            INSTALL_SYSROOT_ARCH="i386"
          fi

          python3 build/linux/sysroot_scripts/install-sysroot.py --arch=${INSTALL_SYSROOT_ARCH}

      - name: Patch
        run: |
          sed -i "s@\"-gsimple-template-names\"@@g" build/config/compiler/BUILD.gn
          sed -i "s@\"-ffile-compilation-dir=.\"@@g" build/config/compiler/BUILD.gn
          sed -i "s@if (is_ubsan && (v8_current_cpu@if ((v8_current_cpu@g" BUILD.gn
          if [[ "${{ matrix.arch }}" == "arm" || "${{ matrix.arch }}" == "x86" ]];then
            sed -i "s@#error@//#error@g" src/base/ubsan.cc
          fi

          rm $NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/12.0.9/lib/linux/x86_64/libatomic.a
          rm $NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/12.0.9/lib/linux/i386/libatomic.a
        env:
            NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build ${{ matrix.arch }}
        run: |
          export PATH=${{ env.DEPOT_TOOLS_PATH }}:$PATH
          which gn
          CURRENT_DIR=$(pwd)
          
          ./build-android.sh ${{ matrix.arch }}
        env:
          NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Copy to dist folder
        run: |
          ls -l ./out/android
          echo "---------------------"
          ls -l ./out/android/obj
          mkdir dist
          cp ./out/android/d8 ./dist/
          cp ./out/android/obj/libv8_monolith.a ./dist/
          cp -r ./include ./dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: v8-android-${{ matrix.arch }}
          path: ./dist

  build_android_fat:
    permissions:
      contents: write
    if: github.event_name == 'release'
    name: "android (fat)"
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Download arm64 artifact
        uses: actions/download-artifact@v3
        with:
          name: v8-android-arm64
          path: v8-android-arm64

      - name: Download arm artifact
        uses: actions/download-artifact@v3
        with:
          name: v8-android-arm
          path: v8-android-arm

      - name: Download x64 artifact
        uses: actions/download-artifact@v3
        with:
          name: v8-android-x64
          path: v8-android-x64

      - name: Download x86 artifact
        uses: actions/download-artifact@v3
        with:
          name: v8-android-x86
          path: v8-android-x86

      - name: Build a fat library
        run: |
          mkdir v8-android-fat
          cp -r ./v8-android-arm64 ./v8-android-fat/arm64-v8a
          cp -r ./v8-android-arm ./v8-android-fat/armeabi-v7a
          cp -r ./v8-android-x64 ./v8-android-fat/x86_64
          cp -r ./v8-android-x86 ./v8-android-fat/x86
          cp -r ./v8-android-arm64/include ./v8-android-fat/
          rm -rf ./v8-android-fat/arm64-v8a/include
          rm -rf ./v8-android-fat/armeabi-v7a/include
          rm -rf ./v8-android-fat/x86_64/include
          rm -rf ./v8-android-fat/x86/include

      - name: Pack dist files
        uses: thedoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        with:
          type: 'zip'
          directory: 'v8-android-fat'
          path: '.'
          filename: 'v8-android.zip'

      - name: Upload to Release
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: v8-android-fat/v8-android.zip
          asset_name: v8-android.zip
          tag: ${{ github.ref }}

